# Generated by Django 2.1.4 on 2018-12-15 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blognote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='blognote',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='followed_user',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='users_followed',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogNote',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
